name: Android APK (Alpha)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
      GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs="-Xmx4g -Dfile.encoding=UTF-8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Generate keystore if missing (alpha signing)
        shell: bash
        run: |
          if [ ! -f keystore.properties ] && [ ! -f release.keystore ]; then
            keytool -genkeypair -v \
              -keystore release.keystore \
              -alias jalmarquest \
              -keyalg RSA -keysize 2048 \
              -validity 10000 \
              -storepass android \
              -keypass android \
              -dname "CN=JalmarQuest Alpha, OU=Development, O=JalmarQuest, L=Unknown, ST=Unknown, C=US" \
              -noprompt
            cat > keystore.properties <<'EOF'
          storeFile=release.keystore
          storePassword=android
          keyAlias=jalmarquest
          keyPassword=android
          EOF
          fi

      - name: Show Gradle tasks for variants (informational)
        run: ./gradlew :app:android:tasks --all --no-daemon | grep -E "assemble(Alpha|Release|Debug)" || true

      - name: Build Release APK (skip tests)
        run: ./gradlew :app:android:assembleRelease -x test --stacktrace --no-daemon

      - name: Fallback to Debug APK (skip tests)
        if: failure()
        run: ./gradlew :app:android:assembleDebug -x test --stacktrace --no-daemon

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jalmarquest-apk-${{ github.sha }}
          path: |
            app/android/build/outputs/apk/**/*.apk
          if-no-files-found: error
